import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#FFF8E7',
  },
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: '#FFF8E7',
  },
  keyboardView: {
    flex: 1,
    justifyContent: 'center',
  },
  inner: {
    maxWidth: 420,
    width: '100%',
    alignSelf: 'center',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 32,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.08)',
    shadowColor: '#000',
    shadowOpacity: 0.5,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 18 },
    elevation: 12,
  },
  title: {
    fontSize: 26,
    fontWeight: '700',
    color: '#1f2937',
    textAlign: 'center',
    marginBottom: 24,
  },
  infoBadge: {
    backgroundColor: 'rgba(234, 88, 12, 0.12)',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 16,
  },
  infoBadgeText: {
    fontSize: 15,
    color: '#c2410c',
    textAlign: 'center',
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.15)',
    borderRadius: 10,
    paddingVertical: 16,
    paddingHorizontal: 14,
    fontSize: 17,
    color: '#1f2937',
    marginBottom: 14,
  },
  btnPrimary: {
    backgroundColor: '#ea580c',
    borderRadius: 10,
    paddingVertical: 18,
    alignItems: 'center',
    marginTop: 6,
    marginBottom: 20,
  },
  btnPrimaryText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
  btnSecondary: {
    backgroundColor: '#FFF8E7',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: 10,
    paddingVertical: 16,
    paddingHorizontal: 18,
    alignItems: 'center',
  },
  btnSecondaryText: {
    color: '#1f2937',
    fontSize: 17,
    fontWeight: '500',
  },
  btnSecondarySmall: {
    marginTop: 4,
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    backgroundColor: '#FFFFFF',
  },
  btnSecondarySmallText: {
    fontSize: 12,
    color: '#1f2937',
  },
  switchText: {
    textAlign: 'center',
    fontSize: 16,
    color: '#6b7280',
  },
  link: {
    color: '#ea580c',
    fontWeight: '500',
  },
  mainShell: {
    flex: 1,
  },
  shellHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  shellTitleGroup: {
    flex: 1,
    paddingRight: 8,
  },
  shellTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1f2937',
  },
  shellSubtitle: {
    marginTop: 4,
    fontSize: 12,
    color: '#6b7280',
  },
  shellUser: {
    alignItems: 'flex-end',
  },
  shellUserInfo: {
    alignItems: 'flex-end',
  },
  shellUserBalance: {
    alignItems: 'flex-end',
    marginTop: 4,
  },
  shellUserLabel: {
    fontSize: 11,
    color: '#6b7280',
  },
  shellUserName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1f2937',
  },
  shellUserCash: {
    fontSize: 13,
    fontWeight: '600',
    color: '#ea580c',
  },
  shellKeyboardView: {
    flex: 1,
  },
  shellScroll: {
    flex: 1,
  },
  shellScrollContent: {
    paddingBottom: 80,
  },
  commonHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFF8E7',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  headerProfileWrap: {
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerProfileIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerProfileEmoji: {
    fontSize: 24,
  },
  commonHeaderTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '600',
    color: '#1f2937',
  },
  headerSettingsWrap: {
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerSettingsIcon: {
    fontSize: 26,
  },
  settingsPopup: {
    position: 'absolute',
    top: 110,
    right: 24,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
    zIndex: 999,
    minWidth: 160,
  },
  settingsPopupSection: { marginBottom: 4 },
  settingsPopupSectionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 10,
  },
  settingsPopupRow: { flexDirection: 'row' },
  settingsPopupItem: { alignItems: 'center', marginHorizontal: 8 },
  settingsPopupIcon: { fontSize: 28, marginBottom: 6 },
  settingsPopupRadio: {
    width: 18,
    height: 18,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: '#d1d5db',
    backgroundColor: '#FFFFFF',
  },
  settingsPopupRadioActive: {
    borderColor: '#ea580c',
    backgroundColor: '#ea580c',
  },
  settingsPopupDivider: {
    height: 1,
    backgroundColor: '#e5e7eb',
    marginVertical: 12,
  },
  bottomTabBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    height: 76,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingBottom: Platform.OS === 'ios' ? 0 : 0,
  },
  bottomTabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  bottomTabItemCenter: {
    flex: 1.1,
  },
  bottomTabIcon: {
    fontSize: 26,
    color: '#9ca3af',
    marginBottom: 2,
  },
  bottomTabIconCenter: {
    fontSize: 30,
  },
  bottomTabLabel: {
    fontSize: 13,
    color: '#9ca3af',
  },
  bottomTabActive: {
    color: '#ea580c',
  },
  homeWrap: {
    marginBottom: 16,
  },
  homeTopBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    marginBottom: 16,
  },
  homeTopBarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeCashIcon: {
    fontSize: 24,
    marginRight: 6,
  },
  homeCashText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1f2937',
  },
  homeTopBarRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeEventIcon: {
    fontSize: 22,
    marginRight: 4,
  },
  homeEventText: {
    fontSize: 16,
    color: '#6b7280',
  },
  homeStepsSection: {
    alignItems: 'center',
    marginBottom: 16,
  },
  homeStepsLabel: {
    fontSize: 20,
    color: '#1f2937',
    marginBottom: 12,
  },
  homeStepsCircle: {
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: '#faedcd',
    borderWidth: 2,
    borderColor: '#e9c46a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeStepsValue: {
    fontSize: 52,
    fontWeight: '900',
    color: '#1f2937',
  },
  homeStepsUnsupportedText: {
    fontSize: 16,
    color: '#6b7280',
    marginTop: 8,
    textAlign: 'center',
  },
  homeStepsScreenTimeLabel: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 4,
  },
  homeStepsScreenTimeValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1f2937',
    marginTop: 2,
  },
  homeMapSection: {
    marginTop: 16,
    marginBottom: 16,
  },
  homeMapTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 12,
  },
  homeMapPlaceholder: {
    height: 160,
    backgroundColor: '#d4edda',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#a8d5b5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeMapPlaceholderText: {
    fontSize: 16,
    color: '#6b7280',
  },
  eventWrap: {
    marginBottom: 16,
  },
  eventTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 24,
  },
  attendanceCheckRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  attendanceCheckItem: {
    flex: 1,
    alignItems: 'center',
    marginHorizontal: 6,
  },
  attendanceCheckLabel: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 8,
  },
  attendanceCheckIcon: {
    fontSize: 46,
    marginBottom: 12,
  },
  attendanceCheckBox: {
    width: 64,
    height: 64,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#ea580c',
    alignItems: 'center',
    justifyContent: 'center',
  },
  attendanceCheckBoxDone: {
    backgroundColor: '#ea580c',
    borderColor: '#ea580c',
  },
  attendanceCheckMark: {
    color: '#FFFFFF',
    fontSize: 34,
    fontWeight: '700',
  },
  eventAdBlock: {
    height: 80,
    backgroundColor: '#e5e7eb',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  eventAdText: {
    color: '#ea580c',
    fontSize: 20,
    fontWeight: '700',
  },
  sectionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.08)',
    marginBottom: 14,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1f2937',
  },
  badgeOutline: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.2)',
  },
  badgeFilled: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: 'rgba(234, 88, 12, 0.15)',
  },
  badgeText: {
    fontSize: 13,
    color: '#c2410c',
  },
  helperText: {
    marginTop: 6,
    fontSize: 14,
    color: '#6b7280',
  },
  attendanceRow: {
    flexDirection: 'row',
  },
  attendancePill: {
    flex: 1,
    marginHorizontal: 2,
    borderRadius: 12,
    padding: 8,
    backgroundColor: '#FFF8E7',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.08)',
  },
  attendanceIcon: {
    width: 22,
    height: 22,
    borderRadius: 999,
    marginBottom: 4,
  },
  attendanceIconMorning: {
    backgroundColor: '#facc15',
  },
  attendanceIconNoon: {
    backgroundColor: '#fb923c',
  },
  attendanceIconEvening: {
    backgroundColor: '#a78bfa',
  },
  attendanceText: {
    marginBottom: 4,
  },
  timeLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#1f2937',
  },
  timeRange: {
    fontSize: 10,
    color: '#6b7280',
  },
  attendanceStatus: {
    fontSize: 10,
    color: '#6b7280',
  },
  lockTime: {
    alignItems: 'center',
    marginBottom: 2,
  },
  lockClock: {
    fontSize: 26,
    fontWeight: '700',
    color: '#1f2937',
  },
  lockDate: {
    fontSize: 11,
    color: '#6b7280',
  },
  lockGiftRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 8,
  },
  lockGiftIcon: {
    width: 60,
    height: 60,
    borderRadius: 16,
    marginHorizontal: 4,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 6,
  },
  lockGiftMorning: {
    backgroundColor: '#facc15',
  },
  lockGiftNoon: {
    backgroundColor: '#fb923c',
  },
  lockGiftEvening: {
    backgroundColor: '#a78bfa',
  },
  lockGiftLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1c1917',
  },
  lockSlide: {
    marginTop: 6,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.5)',
    alignItems: 'center',
  },
  lockSlideText: {
    fontSize: 11,
    color: '#1f2937',
  },
  lockBanner: {
    marginTop: 6,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(0, 0, 0, 0.15)',
    alignItems: 'center',
  },
  lockBannerText: {
    fontSize: 11,
    color: '#6b7280',
  },
  lockScreen: {
    flex: 1,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    backgroundColor: '#FFFFFF',
    paddingVertical: 20,
    paddingHorizontal: 18,
  },
  lockTimeHeader: {
    alignItems: 'center',
    paddingTop: 8,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.08)',
  },
  lockClockLarge: {
    fontSize: 52,
    fontWeight: '700',
    color: '#1f2937',
    letterSpacing: 1,
  },
  lockDateLarge: {
    fontSize: 18,
    color: '#6b7280',
    marginTop: 4,
  },
  lockBody: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lockTop: {
    alignItems: 'center',
    marginBottom: 56,
  },
  lockMiddle: {
    marginBottom: 56,
  },
  lockBottom: {
    width: '100%',
    marginTop: 0,
  },
  lockGreeting: {
    alignItems: 'center',
    paddingHorizontal: 12,
    marginTop: 4,
  },
  lockGreetingText: {
    fontSize: 14,
    color: '#1f2937',
    fontWeight: '600',
    marginBottom: 2,
  },
  lockHintText: {
    fontSize: 12,
    color: '#6b7280',
    textAlign: 'center',
  },
  lockUnlockButton: {
    width: '100%',
    paddingVertical: 20,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.15)',
    backgroundColor: '#FFF8E7',
    alignItems: 'center',
  },
  lockUnlockText: {
    fontSize: 18,
    color: '#1f2937',
  },
  lockNewWrap: {
    flex: 1,
    paddingHorizontal: 24,
  },
  lockNewTopBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
  },
  lockNewTopBarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  lockNewTopBarRight: {
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  lockNewTopBarRightItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  lockNewCashIcon: {
    fontSize: 24,
    marginRight: 6,
  },
  lockNewCashText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1f2937',
  },
  lockNewNavIcon: {
    fontSize: 26,
    marginRight: 6,
  },
  lockNewNavText: {
    fontSize: 16,
    color: '#6b7280',
  },
  lockNewClockWrap: {
    alignItems: 'center',
    marginBottom: 24,
  },
  lockNewClock: {
    fontSize: 60,
    fontWeight: '700',
    color: '#1f2937',
  },
  lockNewDateText: {
    fontSize: 20,
    color: '#6b7280',
    marginTop: 4,
  },
  lockNewStepsSection: {
    alignItems: 'center',
    marginBottom: 24,
  },
  lockNewStepsLabel: {
    fontSize: 18,
    color: '#1f2937',
    marginBottom: 12,
  },
  lockNewStepsCircle: {
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: '#faedcd',
    borderWidth: 2,
    borderColor: '#e9c46a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lockNewStepsValue: {
    fontSize: 60,
    fontWeight: '900',
    color: '#1f2937',
  },
  lockNewGiftOverlay: {
    position: 'absolute',
    fontSize: 48,
  },
  lockNewAdBlock: {
    height: 90,
    backgroundColor: '#e5e7eb',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  lockNewAdText: {
    color: '#ea580c',
    fontSize: 22,
    fontWeight: '700',
  },
  adCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.08)',
    backgroundColor: '#FFF8E7',
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  adHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    marginBottom: 4,
  },
  adHeaderTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1f2937',
  },
  adHeaderSub: {
    fontSize: 11,
    color: '#6b7280',
  },
  adTableHeader: {
    flexDirection: 'row',
    paddingVertical: 2,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.12)',
  },
  adTableRow: {
    flexDirection: 'row',
    paddingVertical: 2,
  },
  adCellText: {
    fontSize: 11,
    color: '#1f2937',
  },
  adCellTitle: {
    flex: 6,
  },
  adCellReward: {
    flex: 3,
    textAlign: 'right',
  },
  adCellDuration: {
    flex: 2,
    textAlign: 'right',
  },
  adRewardPositive: {
    color: '#22c55e',
    fontWeight: '600',
  },
  adFootnote: {
    marginTop: 4,
    fontSize: 10,
    color: '#6b7280',
  },
  storeBalanceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  storeBalanceLabel: {
    fontSize: 15,
    color: '#6b7280',
  },
  storeBalanceValue: {
    fontSize: 17,
    color: '#1f2937',
    fontWeight: '600',
  },
  storeTabs: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  storeTab: {
    flex: 1,
    marginHorizontal: 2,
    paddingVertical: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.12)',
    textAlign: 'center',
    fontSize: 11,
    color: '#6b7280',
  },
  storeTabActive: {
    backgroundColor: 'rgba(234, 88, 12, 0.12)',
    borderColor: '#ea580c',
    color: '#1f2937',
    fontWeight: '600',
  },
  storeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -4,
  },
  productCard: {
    width: '50%',
    paddingHorizontal: 4,
    marginBottom: 8,
  },
  productImage: {
    height: 70,
    borderRadius: 10,
    backgroundColor: 'rgba(234, 88, 12, 0.12)',
    marginBottom: 4,
  },
  productInfo: {
    marginBottom: 4,
  },
  productName: {
    fontSize: 15,
    color: '#1f2937',
  },
  productMeta: {
    fontSize: 13,
    color: '#6b7280',
  },
  productButton: {
    backgroundColor: '#ea580c',
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: 'center',
  },
  productButtonText: {
    fontSize: 15,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  couponTabs: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  couponTab: {
    flex: 1,
    marginHorizontal: 2,
    paddingVertical: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.12)',
    textAlign: 'center',
    fontSize: 11,
    color: '#6b7280',
  },
  couponTabActive: {
    backgroundColor: 'rgba(234, 88, 12, 0.12)',
    borderColor: '#ea580c',
    color: '#1f2937',
    fontWeight: '600',
  },
  couponList: {
    marginTop: 2,
  },
  couponItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
  },
  couponMain: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  couponBrand: {
    width: 32,
    height: 32,
    borderRadius: 999,
    backgroundColor: '#b45309',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  couponBrandText: {
    fontSize: 12,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  couponInfo: {
    flex: 1,
  },
  couponName: {
    fontSize: 15,
    color: '#1f2937',
  },
  couponMeta: {
    fontSize: 13,
    color: '#6b7280',
  },
  couponButton: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(168, 162, 158, 0.8)',
  },
  couponButtonText: {
    fontSize: 15,
    color: '#1f2937',
  },
  placeholderRow: {
    marginTop: 4,
    padding: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 248, 231, 0.8)',
  },
  todaySummary: {},
  todayMain: {
    alignItems: 'center',
    marginBottom: 8,
  },
  todayStepsLabel: {
    fontSize: 11,
    color: '#6b7280',
  },
  todayStepsValue: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1f2937',
  },
  todaySubMetrics: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  metricCard: {
    flex: 1,
    marginHorizontal: 2,
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: '#FFF8E7',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.08)',
  },
  metricLabel: {
    fontSize: 10,
    color: '#6b7280',
  },
  metricValue: {
    marginTop: 2,
    fontSize: 12,
    color: '#1f2937',
  },
  progressRing: {
    marginTop: 4,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(0, 0, 0, 0.15)',
    alignItems: 'center',
  },
  progressRingText: {
    fontSize: 11,
    color: '#6b7280',
  },
  chartTabs: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  chartTab: {
    flex: 1,
    marginHorizontal: 2,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.12)',
    textAlign: 'center',
    fontSize: 11,
    color: '#6b7280',
  },
  chartTabActive: {
    backgroundColor: 'rgba(234, 88, 12, 0.12)',
    borderColor: '#ea580c',
    color: '#1f2937',
    fontWeight: '600',
  },
  chartPlaceholder: {
    height: 120,
    borderRadius: 10,
    backgroundColor: '#FFF8E7',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    marginBottom: 4,
  },
  chartPlaceholderText: {
    fontSize: 11,
    color: '#1f2937',
    textAlign: 'center',
  },
  statsWrap: {
    marginBottom: 16,
  },
  statsCircleSection: {
    alignItems: 'center',
    marginBottom: 24,
  },
  statsCircleTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1f2937',
    textAlign: 'center',
    marginBottom: 12,
  },
  statsCircle: {
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: '#faedcd',
    borderWidth: 2,
    borderColor: '#e9c46a',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  statsCircleValue: {
    fontSize: 42,
    fontWeight: '900',
    color: '#1f2937',
  },
  statsMetricRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statsMetricItem: {
    flex: 1,
    backgroundColor: '#FFF8E7',
    borderRadius: 12,
    padding: 10,
    alignItems: 'center',
    marginHorizontal: 4,
  },
  statsMetricIcon: {
    fontSize: 24,
    marginBottom: 4,
  },
  statsMetricValue: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1f2937',
  },
  statsMetricUnit: {
    fontSize: 14,
    color: '#6b7280',
    marginTop: 2,
  },
  statsGraphSection: {
    marginTop: 8,
  },
  statsGraphTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 12,
  },
  statsGraphNote: {
    fontSize: 13,
    color: '#6b7280',
    textAlign: 'center',
    marginTop: 12,
  },
  historyFilters: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  historyFilter: {
    flex: 1,
    marginHorizontal: 2,
    paddingVertical: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.12)',
    textAlign: 'center',
    fontSize: 10,
    color: '#6b7280',
  },
  historyFilterActive: {
    backgroundColor: 'rgba(234, 88, 12, 0.12)',
    borderColor: '#ea580c',
    color: '#1f2937',
    fontWeight: '600',
  },
  historyList: {
    marginTop: 2,
  },
  historyItem: {
    flexDirection: 'row',
    paddingVertical: 12,
  },
  historyIcon: {
    width: 26,
    height: 26,
    borderRadius: 999,
    backgroundColor: '#d6d3d1',
    marginRight: 8,
  },
  historyIconAttendance: {
    backgroundColor: '#22c55e',
  },
  historyContent: {
    flex: 1,
  },
  historyTitle: {
    fontSize: 16,
    color: '#1f2937',
    fontWeight: '600',
  },
  historyBody: {
    fontSize: 14,
    color: '#6b7280',
  },
  historyTime: {
    fontSize: 13,
    color: '#6b7280',
  },
  alarmTableHeader: {
    flexDirection: 'row',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    marginTop: 12,
  },
  alarmTableRow: {
    flexDirection: 'row',
    paddingVertical: 6,
  },
  alarmTableCell: {
    paddingHorizontal: 4,
  },
  alarmTableColDate: { flex: 3 },
  alarmTableColTime: { flex: 2 },
  alarmTableColStatus: { flex: 1 },
  alarmTableHeaderText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1f2937',
  },
  alarmTableCellText: {
    fontSize: 14,
    color: '#6b7280',
  },
  cashPeriodRow: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  periodButton: {
    flex: 1,
    marginHorizontal: 2,
    paddingVertical: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(87, 83, 78, 0.9)',
    textAlign: 'center',
    fontSize: 10,
    color: '#6b7280',
  },
  periodButtonActive: {
    backgroundColor: 'rgba(234, 88, 12, 0.12)',
    borderColor: '#ea580c',
    color: '#1f2937',
    fontWeight: '600',
  },
  cashList: {},
  cashItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
  },
  cashAmountPositive: {
    width: 90,
    fontSize: 16,
    color: '#22c55e',
    fontWeight: '700',
  },
  cashAmountNegative: {
    width: 90,
    fontSize: 16,
    color: '#ef4444',
    fontWeight: '700',
  },
  cashInfo: {
    flex: 1,
  },
  cashReason: {
    fontSize: 16,
    color: '#1f2937',
  },
  cashMeta: {
    fontSize: 13,
    color: '#6b7280',
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  profileAvatar: {
    width: 60,
    height: 60,
    borderRadius: 999,
    backgroundColor: '#ea580c',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  profileAvatarText: {
    fontSize: 14,
    color: '#FFFFFF',
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1f2937',
  },
  profileMeta: {
    fontSize: 14,
    color: '#6b7280',
  },
  profileMenu: {},
  profileMenuItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(120, 113, 108, 0.5)',
  },
  profileMenuText: {
    fontSize: 16,
    color: '#1f2937',
  },
  profileMenuChevron: {
    fontSize: 16,
    color: '#6b7280',
  },
  profileMenuDanger: {},
  profileMenuDangerText: {
    color: '#f97373',
  },
  guardianRow: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  guardianInputGroup: {
    flex: 1,
    marginHorizontal: 2,
  },
  guardianLabel: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 4,
  },
  selectBox: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.15)',
    paddingVertical: 16,
    paddingHorizontal: 12,
    backgroundColor: '#FFFFFF',
  },
  selectBoxText: {
    fontSize: 16,
    color: '#1f2937',
  },
  guardianActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
    gap: 10,
  },
  guardianBtn: {
    flex: 1,
    height: 56,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  guardianBtnSecondary: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.2)',
  },
  guardianBtnSecondaryText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
  },
  guardianBtnPrimary: {
    backgroundColor: '#ea580c',
  },
  guardianBtnPrimaryText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  guardianList: {},
  guardianItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
  },
  guardianPriority: {
    width: 40,
    fontSize: 14,
    color: '#ea580c',
    fontWeight: '600',
  },
  guardianMain: {
    flex: 1,
  },
  guardianName: {
    fontSize: 16,
    color: '#1f2937',
  },
  guardianMeta: {
    fontSize: 13,
    color: '#6b7280',
  },
  guardianInlineActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  guardianActionBtn: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ea580c',
    backgroundColor: 'rgba(234, 88, 12, 0.08)',
    marginLeft: 6,
  },
  guardianActionBtnText: {
    fontSize: 14,
    color: '#ea580c',
    fontWeight: '600',
  },
  guardianActionBtnDanger: {
    borderColor: '#f97373',
    backgroundColor: 'rgba(249, 115, 115, 0.08)',
  },
  guardianActionBtnDangerText: {
    fontSize: 14,
    color: '#f97373',
    fontWeight: '600',
  },
  linkSmall: {
    fontSize: 13,
    color: '#ea580c',
    fontWeight: '600',
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  linkSmallDanger: {
    color: '#f97373',
  },
  settingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  settingLabels: {
    flex: 1,
    marginRight: 6,
  },
  settingTitle: {
    fontSize: 16,
    color: '#1f2937',
    fontWeight: '500',
  },
  settingDesc: {
    fontSize: 14,
    color: '#6b7280',
  },
  settingValue: {
    fontSize: 16,
    color: '#1f2937',
    fontWeight: '500',
  },
  switchBox: {
    width: 60,
    height: 32,
    borderRadius: 999,
    backgroundColor: '#22c55e',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  switchKnob: {
    width: 26,
    height: 26,
    borderRadius: 999,
    backgroundColor: '#f9fafb',
    justifyContent: 'center',
    alignItems: 'center',
  },
  switchKnobOn: {
    alignSelf: 'flex-end',
  },
  switchKnobOff: {
    alignSelf: 'flex-start',
  },
  stepperBtn: {
    width: 48,
    height: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.15)',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperBtnText: {
    fontSize: 20,
    color: '#1f2937',
    fontWeight: '600',
  },
  switchTextLabel: {
    fontSize: 9,
    color: '#16a34a',
    fontWeight: '700',
  },
  fullWidthButton: {
    marginTop: 8,
  },
  toast: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 40,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 999,
    alignItems: 'center',
  },
  toastSuccess: {
    backgroundColor: '#22c55e',
  },
  toastError: {
    backgroundColor: '#ef4444',
  },
  toastText: {
    color: '#f9fafb',
    fontSize: 16,
    fontWeight: '500',
  },
});

export default styles;

